# Ansible playbook for my tumbleweed work machine
---

- hosts: localhost
- name: Install vscode
  hosts: localhost

  become: true

  tasks:
    - name: check if vs-code is installed
      shell: code --version
      register: code_version_cmd
      changed_when: false
      ignore_errors: true
      become: false

    - name: add microsoft key
      shell: rpm --import https://packages.microsoft.com/keys/microsoft.asc
      when: code_version_cmd is failed

    - name: add microsoft repo
      shell: zypper addrepo https://packages.microsoft.com/yumrepos/vscode vscode
      when: code_version_cmd is failed

    - name: install vs-code
      zypper:
        name: code
        state: present
        refresh: yes
      when: code_version_cmd is failed

- name: Install activate-linux
  hosts: localhost
  become: true
  tasks:
    - name: check if activate-linux is installed
      shell: activate-linux --help
      register: activate_linux_cmd
      changed_when: false
      ignore_errors: true
      become: false

    - name: add tschmitz-activate-linux key
      shell: rpm --import https://download.opensuse.org/repositories/home:/tschmitz:/activate-linux/openSUSE_Tumbleweed/repodata/repomd.xml.key
      when: activate_linux_cmd is failed

    - name: add microsoft repo
      shell: zypper addrepo https://download.opensuse.org/repositories/home:tschmitz:activate-linux/openSUSE_Tumbleweed/home:tschmitz:activate-linux.repo
      when: activate_linux_cmd is failed

    - name: install activate-linux
      zypper:
        name: activate-linux
        state: present
        refresh: yes
      when: activate_linux_cmd is failed

- name: Install mambaforge
  hosts: localhost
  become: true
  tasks:
    - name: check if mambaforge is installed
      shell: conda --help
      register: mambaforge_cmd
      changed_when: false
      ignore_errors: true
      become: false

    - name: run mambaforge install script
      shell: curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh" && bash Mambaforge-$(uname)-$(uname -m).sh
      when: mambaforge_cmd is failed


- name: Install desktop applications
  hosts: localhost

  tasks:
    - zypper:
        name: flatpak
        state: present
      become: true

    - flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - flatpak:
        name: org.chromium.Chromium
        state: present
        method: user

    - flatpak:
        name: flatseal
        state: present
        method: user

    - flatpak:
        name: com.mattjakeman.ExtensionManager
        state: present
        method: user

    - flatpak:
        name: com.slack.Slack
        state: present
        method: user

    - flatpak:
        name: com.microsoft.Teams
        state: present
        method: user

    - flatpak:
        name: org.openmw.OpenMW
        state: present
        method: user

    - flatpak:
        name: com.github.KRTirtho.Spotube
        state: absent
        method: user

    - flatpak:
        name: im.riot.Riot
        state: present
        method: user

    - flatpak:
        name: org.signal.Signal
        state: present
        method: user

    - flatpak:
        name: org.openttd.OpenTTD
        state: present
        method: user

    - flatpak:
        name: net.ankiweb.Anki
        state: present
        method: user

- name: Install packages
  hosts: localhost
  become: true

  tasks:
    - zypper:
        name: python3-pip
        state: present

    - zypper:
        name: git
        state: present

    - zypper:
        name: fish
        state: present

    - zypper:
        name: gnome-pomodoro
        state: present

    - zypper:
        name: make
        state: present

    - zypper:
        name: typescript
        state: present

    - zypper:
        name: NetworkManager-openconnect-gnome
        state: present

    - zypper:
        name: tealdeer
        state: present

    - zypper:
        name: neofetch
        state: present

    - zypper:
        name: clang
        state: present

    - zypper:
        name: devel_basis
        state: present
        type: pattern

    - zypper:
        name: neovim
        state: present

    - zypper:
        name: onedrive
        state: present

    - zypper:
        name: yt-dlp
        state: present

    - zypper:
        name: PackageKit
        state: absent

- name: change shell to fish
  hosts: localhost

  tasks:
    - user:
        name: hagenest
        shell: /usr/bin/fish
      become: true

- name: Update system
  hosts: localhost

  tasks:
    - name: update zypper packages
      zypper:
        name: '*'
        state: latest
      become: true

- name: Update tldr cache
  hosts: localhost

  tasks:
    - name: update tldr cache
      shell: tldr --update

- name: Install spacevim
  hosts: localhost
  tasks:
    - name: install spacevim
      shell: curl -sLf https://spacevim.org/install.sh | bash
      register: spacevim_install

- name: Add username and email to gitconfig
  hosts: localhost
  tasks:
  - shell: git config --global user.name 'Christian Hagenest' && git config --global user.email 'christian.hagenest@suse.com'

- name: Create OneDrive directory + symlink to Documents
  hosts: localhost
  tasks:
  - file:
      path: ~/OneDrive
      state: directory
      mode: '0755'
      owner: 'hagenest'
  # - file:
  #     src: ~/Documents
  #     dest: ~/OneDrive/Documents
  #     owner: hagenest
  #     state: hard
